# Generated by Django 2.1 on 2018-11-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='كود المستخدم')),
                ('RPODateAdded', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تاريخ المكافأة')),
                ('RPODescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الوصف')),
                ('RPOPoints', models.IntegerField(blank=True, null=True, verbose_name='عدد النقاط')),
                ('RPOSlug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'نقطة مكافأة',
                'verbose_name_plural': 'نقاط المكافآت',
            },
        ),
    ]
