# Generated by Django 2.1 on 2018-11-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0003_auto_20181116_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('addreess', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='user_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duplicate.UserModel', verbose_name='المستخدم'),
        ),
    ]
