# Generated by Django 2.1 on 2018-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0004_auto_20181116_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'الموظف',
                'verbose_name_plural': 'الموظفين',
            },
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AddField(
            model_name='lead',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='duplicate.Employee'),
        ),
    ]
