# Generated by Django 2.1 on 2018-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0006_lead_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='employee',
            field=models.ManyToManyField(to='duplicate.Employee'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
