# Generated by Django 2.0.8 on 2018-11-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duplicate', '0009_auto_20181116_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='duplicate.Employee'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duplicate.UserModel', verbose_name='المستخدم'),
        ),
    ]
